.gitignore, Cargo.toml, src/gossip_agent/mod.rs, src/gossip_agent/waku_handling.rs, src/lib.rs, src/records_to_tree.rs
Utilize CLI [tool](https://github.com/status-im/nim-dnsdisc) `tree_creator` to generate a ENR record tree signed by a consistent key pair. 
Manually set up DNS records on Cloudflare under the domain `graphcast.xyz`, then provide the ENR tree url for peer discovery.
Configurable tree url with fallback default at `enrtree://AMRFINDNF7XHQN2XBYCGYAYSQ3NV77RJIHLX6HJLA6ZAF365NRLMM@graphcast.xyz`
Resolves #15 
-> later set up automated process for keeping the record tree updated
=> feat: peer discovery with consistent DNS enrtree url

Cargo.lock, Cargo.toml, src/gossip_agent/waku_handling.rs
This PR updates waku dependency path such that the `graphcast` crate can be published.
The new Discv5 feature is currently not used.
=> feat: crates publication ready

examples/ping-pong/src/main.rs, examples/ping-pong/src/types.rs, src/gossip_agent/message_typing.rs, src/gossip_agent/mod.rs, src/gossip_agent/waku_handling.rs, src/records_to_tree.rs
For different radio use cases, the structure of the radio payloads inside `GraphcastMessage` must be flexible. This PR allows Radio specific message definitions to be passed in as a generic protobuf `message` field in the `GraphcastMessage`. 
Individual radios are responsible for satisfying 
- [Eip712](https://eips.ethereum.org/EIPS/eip-712) standard for message hashing and signing and 
- [Protobuf](https://docs.rs/prost/latest/prost/index.html) types for encoding and decoding during transmission. 
Example Radio message definition
```
/// Required packages
use ethers_core::types::transaction::eip712::Eip712;
use ethers_derive_eip712::*;
use prost::Message;
use serde::{Deserialize, Serialize};
/// Auto trait derivations for radio message. Example  with 2 fields
#[derive(Eip712, EthAbiType, …
```
=> Generic radio payload message typing

examples/ping-pong/src/main.rs, src/gossip_agent/mod.rs, src/gossip_agent/waku_handling.rs, src/lib.rs, src/records_to_tree.rs
- Utilize Cloudflare DNS nameserver for discovery
- Allow users to provide customized multiaddress to advertise to peers
- Update logs to be more accurate for connected peers
- Use exposed IP endpoint 
Closes #55
=> fix: utilize cf nameserver, advertise multiaddress

examples/ping-pong/src/main.rs, src/gossip_agent/mod.rs, src/gossip_agent/waku_handling.rs
Before sending a message, the gossip client checks for network connectivity with the established known peers, and attempts to reconnect if the peer has been disconnected. This will allow nodes to assume as normal without manual restart when service nodes are rebooted.
Further consideration is that client is doing more work per sending of message, so it could be a good idea to check connectivity less frequent, but also made sense to do so before sending a message since they are only connected to routing nodes so far.
Closes #60
=> Automatic reconnect to peers

examples/ping-pong/src/main.rs, src/gossip_agent/message_typing.rs, src/gossip_agent/mod.rs, src/gossip_agent/waku_handling.rs, src/graphql/client_network.rs, src/lib.rs, src/tree_to_txt.rs
Refactor topic generations for more flexible usage for 3LA initialization - if no subtopic is provided, then no filtering for the messages. 
Reduce the size of Gossip agent to not keep track of indexer address and allocations. 
Closes #62
=> Refactor topics and Gossip agent

Cargo.lock, examples/ping-pong/src/main.rs, src/gossip_agent/mod.rs, src/gossip_agent/waku_handling.rs, src/lib.rs
This PR removes the need to use a file to store a boot note multiaddr. Because now a light node will try to connect to active boot nodes by default, it's not needed to first run a boot node and store the multiaddr in a file and then running a light node that uses that boot node id. With this PR a boot node multiaddr can be passed in with an env variable, and it will be used if the light node cannot find a hosted boot node.
Next steps:
Currently there are a lot of scattered environment variables around the codebase, we should use something like [clap](https://github.com/clap-rs/clap) to manage environment variables on application startup.
=> refactor: improve boot node logic

.github/dependabot.yml, Cargo.lock, Cargo.toml
Suppose to resolve dependency on crates `time` and `tokio`, could not update lower level dependency on `failure`.
https://github.com/graphops/graphcast-sdk/security/dependabot
=> chore: dependency update

Cargo.lock, Cargo.toml, src/gossip_agent/message_typing.rs, src/gossip_agent/mod.rs, src/gossip_agent/waku_handling.rs
- Update protocol connection mechanism to use Filter protocol
- Utilizes Filter subscription and removed custom content topic check
- Add pubsub topic in waku node initiation as `relay_topics`
- Minor refactoring of related logs
- Added fields for `Discv5` but not utilized yet
Testing needed before merge
Resolves #49
=> feat: bump waku binding with filter and relay topic

examples/ping-pong/src/main.rs, src/graphcast_agent/message_typing.rs, src/graphcast_agent/mod.rs, src/graphcast_agent/waku_handling.rs, src/graphql/client_registry.rs, src/lib.rs
Rename relevant variable names to use `Graphcast` instead of `Gossip`
Resolves #79
=> refactor: rename agent to graphcast

Cargo.lock, Cargo.toml
Update crates.io path to git commit version on `0.0.1-beta3` to avoid the breaking changes within the prerelease of beta4
Update for dependency resolution conflict with graphops/poi-radio#30
=> dependency path to git commit of waku-bindings 0.0.1-beta3

Cargo.lock, Cargo.toml, examples/ping-pong/src/main.rs, src/graphcast_agent/message_typing.rs, src/graphcast_agent/mod.rs, src/graphcast_agent/waku_handling.rs
Added a function to add new content topics to the filter protocol subscriptions.
- To make better update process such as to unsubscribe old topics, we need to make graphcast object mutable, which then require many operations to be unsafe
- We can later discuss how should the older topics be removed, if it should be some period after the indexer/operator has moved away from a particular Graph entity such as closing an allocation
I wanted to make a curried function similar to register signal handler, but want to first leave more control for individual radio to make periodic calls for updates as well as the query function structure
Partially resolves graphops/poi-radio#32
=> content topic poll and update

Cargo.lock, Cargo.toml, examples/ping-pong/src/main.rs, src/graphcast_agent/message_typing.rs, src/graphcast_agent/mod.rs, src/graphcast_agent/waku_handling.rs, src/graphql/client_network.rs, src/graphql/client_registry.rs, src/lib.rs
Added `EnvFilter` logs configuring log levels, added error variants to replace mostly all of the anyhow errors
Example usage: `RUST_LOG="off,hyper=off,graphcast_sdk=debug,ping_pong=debug"`
This doesn't include waku logs but should be fixed soon.
graphops/poi-radio#10
=> refactor: log filters and new error variants

examples/ping-pong/src/main.rs, src/graphcast_agent/message_typing.rs, src/graphcast_agent/mod.rs, src/graphcast_agent/waku_handling.rs
Adding a set of old message IDs for the local message sent and the first peer message received. Manually check and filter for messages to go through validation and store process, error out early if message was seen already.
Fixes #98 and #102
=> fix: unique peer message filter

.github/dependabot.yml, .github/release.yml, Cargo.lock, Cargo.toml, scripts/release.sh
Adding automated release note generation
Also, bumping waku crates version that contains the log level fix (doesn't seem to respect it still :(
Resolves #41
=> feat: automated release script

Cargo.lock, Cargo.toml, examples/ping-pong/src/main.rs, src/config.rs, src/graphcast_agent/message_typing.rs, src/graphcast_agent/mod.rs, src/graphcast_agent/waku_handling.rs, src/graphql/client_graph_node.rs, src/graphql/client_network.rs, src/graphql/client_registry.rs, src/lib.rs
Added validations to a couple of the start-up configurations
- graph_node_endpoint - by an indexing statuses query
- private_key - by parsing to an Ethereum wallet
- registry_subgraph - by indexer id query
- network_subgraph - by indexer_stake query
- graphcast_network - limited to mainnet or testnet, can be relaxed later
- collect_message_duration - minimum set to 0
- boot_node_addresses - by parsing to MultiAddr
- log_level - by setting up the logger
Skipping
- topics - no validation needed
- waku_host, waku_port, waku_node_key, waku_log_level - Waku input get validated when creating Graphcast agent
Later add validation to optional arguments if they were provided
- metrics_url
- slack_token
- slack_webhook
Improved SDK logs to 
- Remove info logs on "Message Received" and "Sent message …
=> basic args validation and improve logs

examples/ping-pong/src/main.rs, src/config.rs, src/graphcast_agent/message_typing.rs, src/graphcast_agent/mod.rs, src/graphql/client_graph_node.rs, src/lib.rs, src/networks.rs
Require either private key or mnemonics as the input to build Graphcast ID wallet
Check
```rust
// Validity error
'Could not validate the supplied configurations: Validate the input: The registry subgraph did not contain an entry for the Graphcast ID to Indexer: Query response is unexpected: No indexer data queried from registry for GraphcastID: 0xe9a1cabd57700b17945fd81feefba82340d9568f'
// Missing argument error
thread 'main' panicked at 'Could not validate the supplied configurations: Validate the input: Must provide either private key or mnemonics', examples/ping-pong/src/main.rs:32:9
// Happy
DEBUG graphcast_sdk::config: Resolved indexer stake: 9884362578232080096242390
```
Refactored NETWORKS configurations to its own file
Resolves #139
Resolves #138
=> feat: mnemonics allowed, refactor network config

pull_request_template.md, src/graphcast_agent/waku_handling.rs
- Updated the waku node config to only use filter protocol by disabling relay protocol and pubsub topic there.
- Removed related check on content topics.
- Updated a typo in pull request template
Got help from waku team waku-org/waku-rust-bindings#54
Resolves last task of #35
=> fix: waku node setup with filter protocol only

src/graphcast_agent/message_typing.rs, src/graphql/schema_graph_node.graphql
There was a bug that some `indexingStatuses` has null `node` which is allowed by graph-node schema, but our definition made it strictly non-null. In this PR we update the field type, along with a few new fields (`latestHealthyBlock` for chains, `deterministic` for failed block, `Healthy` enum).
Helps with graphops/poi-radio#85
=> Fix indexing statuses schema

src/config.rs, src/graphcast_agent/mod.rs
- Add metrics host to configuration, "0.0.0.0" is the fallback.
- Remove -1 from peer_count for the Waku API
Follow up to #163
=> feat: add metrics_host to config

Cargo.lock, Cargo.toml, examples/ping-pong/src/types.rs, src/config.rs, src/graphcast_agent/message_typing.rs, src/graphcast_agent/mod.rs, src/graphcast_agent/waku_handling.rs, src/lib.rs
To allow GraphQL queries to a `GraphcastMessage` entity, make the trait and restrict entity requirement to the generic typing to require defined `GraphQL outputType`.
Depended by graphops/poi-radio #92
=> Create GraphcastMessage GraphQL Output type and API server config

Cargo.lock, Cargo.toml, changelog.md, scripts/release.sh, src/graphcast_agent/mod.rs
Comment out unsubscribe until waku-rust-binding creates a new crate that includes this fix: https://github.com/waku-org/go-waku/pull/536 
- Agents temporarily cannot unsubscribe to older topics
- [] Are tests up-to-date with the new changes?
=> subscription unsubscribe disabled

Cargo.lock, examples/ping-pong/src/main.rs, src/graphcast_agent/message_typing.rs, src/graphcast_agent/mod.rs, src/graphcast_agent/waku_handling.rs
Allow Graphcast agent to participate in filter protocol xor relay protocol. This is to enable 3LA agents to monitor all messages without needing to filter for specific content topics.
- with filter protocol, subscriptions to peers are specific to content topics from a custom generation topic and the subscription set is periodically updated.
- with relay protocol, subscriptions are specific to a pubsub topic for all peers. 
Note that Waku default to the protocols is relay and not filter. Our desired default is filter and not relay as it is expected that most clients would not want to handle all messages on the network. Thus unless specified by user config, the agent should automatically assume filter protocol. 
Enable 3LA https://github.com/graphops/graphcast-3la/issues/4
=> Gossip protocol toggle

examples/ping-pong/src/config.rs, examples/ping-pong/src/main.rs, src/callbook.rs, src/graphcast_agent/message_typing.rs, src/graphcast_agent/mod.rs, src/graphcast_agent/waku_handling.rs, src/graphql/client_graph_account.rs, src/graphql/client_network.rs, src/graphql/client_registry.rs, src/graphql/mod.rs, src/graphql/query_graph_account.graphql, src/graphql/query_network.graphql, src/graphql/schema_graph_account.graphql, src/lib.rs
- Add options for ways to validate the sender for a Graphcast Message. The option is used for validating local account identity during pre-operational validation and when the radio receives remote messages.
- Add a field `graph_account` to `GraphcastMessage` for resolution between `indexer_opeartor` and `indexer_address` since the relationship can be N-to-N. The sender of the message must be able to resolve into the claimed `graph_account` through the configured validation mechanism
- Add new queries for `GraphAccount`, laying the groundwork for checking message senders who can be non-indexers. It is later possible to utilize "subgraphs{id}" to check for subgraph ownerships so that subgraph owners can send GraphcastMessage as well.
- Fix DNS enr info encoding as base64 
Available options …
=> feat: validation mechanism options for msg sender identity

examples/ping-pong/src/main.rs, src/callbook.rs, src/graphcast_agent/message_typing.rs, src/graphcast_agent/mod.rs, src/graphql/client_graph_account.rs, src/graphql/client_graph_node.rs, src/graphql/client_network.rs, src/graphql/client_registry.rs, src/graphql/mod.rs, src/lib.rs
There was a lot of use of the owned String type without necessity. Cases where the value is being used for comparison, or just to read &str is a better option. Unnecessary clones were removed too and .to_string() calls added as needed. Functions like ::new still use String to makes things easier.
I didn't check on `poi-radio`, but I think a few calls might need to change there.
=> refactor: String -> &str

Cargo.lock, Cargo.toml
syntax to strictly require dependency with `crate_name = "=x.y.z"`
=> chore: fix waku version

examples/ping-pong/src/config.rs, examples/ping-pong/src/main.rs, examples/ping-pong/src/types.rs, src/graphcast_agent/message_typing.rs, src/graphcast_agent/mod.rs, src/graphcast_agent/waku_handling.rs, src/graphql/client_graph_account.rs, src/graphql/client_network.rs, src/graphql/query_graph_account.graphql, src/graphql/schema_graph_account.graphql, src/lib.rs
- id_validation variant `SubgraphStaker` allows messages verified with the identity of subgraph owner or an indexer. 
- The specific check for subgraph ownership between subgraph and graph account can happen on the radio message type. 
- curators and delegators not verified
- Updated `graphcast_agent` and `handle_signal` to utilize MPSC to avoid async handling of waku messages. 
- Removed `
Add function to check a graph_account is the subgraph owner for a certain deployment. 
Resolves https://github.com/graphops/graphcast-sdk/issues/254
The history of this branch is a bit messy, should rebase after merging the previous branches and make sure changes are consistent
=> generic message decode + subgraph owner check

.github/workflows/labels.yml
updated `awaiting-triage` to `meta:awaiting-triage`
=> chore: update labels workflow
