graphops/graphcast-sdk

.gitignore, Cargo.toml, contributing.md, examples/ping-pong/Cargo.lock, examples/ping-pong/src/main.rs, src/gossip_agent/message_typing.rs, src/gossip_agent/mod.rs, src/gossip_agent/waku_handling.rs, src/graphql/client_network.rs, src/lib.rs
Switch to using [tracing](https://crates.io/crates/tracing) instead of `println!()` for logging. 
Next steps:
- Add support for Prometheus (check out [this guide](https://tokio.rs/tokio/topics/tracing-next-steps))
=> refactor: improve logging (add tracing crate)

Cargo.toml, examples/ping-pong/src/main.rs, src/gossip_agent/message_typing.rs, src/gossip_agent/mod.rs, src/gossip_agent/waku_handling.rs, src/graphql/client_network.rs, src/lib.rs, src/tree_to_txt.rs
First step to improve SDK error handling, parking it for now as there are more pressing Issues.
=> refactor: improve error handling

examples/ping-pong/src/main.rs, src/graphcast_agent/message_typing.rs, src/graphcast_agent/mod.rs, src/graphql/client_network.rs, src/graphql/client_registry.rs, src/graphql/query_registry.graphql, src/graphql/schema_registry.graphql, src/lib.rs
Given the new [registry subgraph](https://thegraph.com/hosted-service/subgraph/juanmardefago/graphcast-registry), update the query path, query string, schema, and parse function.
Resolves #82
=> Update registry query

Cargo.lock, Cargo.toml, src/graphcast_agent/message_typing.rs
Saw this in the PR but forgot to comment (sorry)
=> refactor: remove redundant log

.cargo/config.toml, Cargo.lock, Cargo.toml, src/graphcast_agent/waku_handling.rs
Bumped bindings to `beta4`. Also fixed the weird Go compilation issue.
=> chore: bump waku bindings

Cargo.lock, Cargo.toml, examples/ping-pong/src/main.rs, src/graphcast_agent/message_typing.rs, src/graphcast_agent/mod.rs, src/graphcast_agent/waku_handling.rs
Use this branch for testing the POI radio, manually filtering messages to be subscribed content topic
Resolves graphops/poi-radio#39
=> refactor: check topics upon receive

examples/ping-pong/src/main.rs, src/graphcast_agent/waku_handling.rs, src/lib.rs
Closes #106 
```
mainnet ENR url: "enrtree://APDKVCM3Q7TLTBD2FXKMXNIOIDPQRXNNI4ZXKEQLOWAFO3BZXZM3C@mainnet.bootnodes.graphcast.xyz"
testnet+default ENR url: "enrtree://AOADZWXPAJ56TIXA74PV7VJP356QNBIKUPRKR676BBOOELU5XDDKM@testnet.bootnodes.graphcast.xyz"
```
=> feat: auto resolve dns url by pubsub topic

examples/ping-pong/src/main.rs, src/graphcast_agent/message_typing.rs, src/graphcast_agent/mod.rs, src/graphcast_agent/waku_handling.rs
- Minor refactoring
- Added check within `valid_sender` to avoid the same address from the operator
Closes #102
=> fix: explicit indexer address check

src/graphcast_agent/message_typing.rs, src/graphcast_agent/waku_handling.rs
=> Fix: Additional sender id check

Cargo.lock, Cargo.toml
=> chore: publish to crates.io

.github/release.yml
Added refactor and bug fix section
follow up to #119
=> Release notes sections added

README.md
*Add a brief overview of the changes and motivation behind them here*
Fixed a grammatical error on the readme
N/A
=> fix: Fixed a grammatical error on the readme

.github/workflows/auto-approve-n-merge.yml
Annoyed with the dependabot PRs so let's automate them further 😵‍💫 
Don't want to include a personal access token, so hoping the [GITHUB token](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) generated for each workflow is sufficient!
=> Dependabot auto approve and merge

src/graphcast_agent/mod.rs
Fixes https://github.com/graphops/graphcast-sdk/issues/147
=> bugfix: fix peer count issue

src/config.rs
Adds optional prometheus toggle
=> feat: add prometheus toggle

pull_request_template.md
Updated the pull request template to add a checklist. I've added this checklist so we can ensure that we're more diligent with our pull requests.
N/A
=> fix: Updated pull request template

.github/workflows/auto-approve-n-merge.yml
This reverts commit b6069bd01c2a2f663552c1d2c560533ad244dc22.
*Add a brief overview of the changes and motivation behind them here*
[Link to issue]()
=> Revert "feat: auto approve and merge pr by dependabot (#149)"

src/graphcast_agent/mod.rs
As described in [issue](https://github.com/graphops/poi-radio/issues/115), we found that radios would get stuck after an update to content topics. 
This PR modifies the update process and ensure that the lock to content topics is dropped after update. In theory, the lock should be automatically updated once the update process goes out of scope, but the logs returned by indexers showed that the update thread was paused and cached without ever releasing the content_topics variable.
indexer 1:
```
2023-04-26T17:21:55.827343Z INFO poi_radio::attestation: Operation summary for Chainhead blocks: { arbitrum-one: 84556047, avalanche: 29254485, mainnet: 17131857, celo: 18972300, gnosis: 27644724 }: # of deployments tracked: 9 # of deployment updates sent: 7 # of deployments waiting for next …
```
=> release topics lock

Cargo.lock, Cargo.toml, changelog.md, scripts/release.sh
=> chore: release v0.1.2

Cargo.lock, Cargo.toml, src/graphcast_agent/message_typing.rs, src/graphcast_agent/mod.rs, src/graphcast_agent/waku_handling.rs
Accommodate breaking changes introduced in the new waku version
=> Waku-bindings and other dep updates

Cargo.lock, Cargo.toml, examples/ping-pong/src/config.rs, examples/ping-pong/src/main.rs, src/graphcast_agent/message_typing.rs, src/graphcast_agent/mod.rs, src/graphcast_agent/waku_handling.rs, src/graphql/client_graph_node.rs, src/graphql/client_network.rs, src/graphql/client_registry.rs, src/lib.rs
Added formatted configurable logging: `full`, `compact`, `json`, and `pretty`. Below are their respective examples
#174
=> logger formats

README.md, src/graphql/client_registry.rs, src/graphql/query_registry.graphql, src/graphql/schema_registry.graphql
Refactored the GraphcastRegistry contract and updated the Registry subgraph. 
Refactored the query to resolve graphcast_id with an indexer.
Modified README matrix.
Follow up to graphops/graphcast-registry#13
=> refactor: update query for new registry subgraph schema

Cargo.lock, Cargo.toml, src/bots.rs, src/graphcast_agent/waku_handling.rs
Adds Telegram bot support
https://github.com/graphops/poi-radio/issues/121
=> feat: add Telegram bot support

examples/ping-pong/src/main.rs, src/graphcast_agent/mod.rs
Enables https://github.com/graphops/poi-radio/pull/168
=> refactor: change radio_name to be String

.github/workflows/auto-approve-n-merge.yml, Cargo.lock, Cargo.toml, src/graphcast_agent/mod.rs, src/graphcast_agent/waku_handling.rs
=> chore: update dep versions

src/graphcast_agent/message_typing.rs, src/graphql/client_graph_account.rs
Deal with the case when indexer doesn't have an operator, so indexer without operator or graphcast id can directly send messages and be validated
=> fix: allow indexer without operator

examples/ping-pong/src/main.rs, src/graphcast_agent/message_typing.rs, src/graphcast_agent/mod.rs, src/graphql/client_graph_node.rs, src/graphql/client_network.rs
=> refactor: remove some unnecessary clones

Cargo.lock, examples/ping-pong/src/main.rs, src/graphcast_agent/message_typing.rs, src/graphcast_agent/mod.rs
Require payload to come with every Graphcast message
Partially resolve #245
=> refactor: graphcast message requires payload

examples/ping-pong/src/main.rs, src/graphcast_agent/message_typing.rs, src/graphcast_agent/mod.rs, src/lib.rs
- require GraphcastMessage to come with a payload message field
- remove block_number, block_hash, and network from GraphcastMessage, expect Radio message to specify and validate if needed
- remove 
Partially resolve #245
=> Message layer restructure

.github/workflows/labels.yml
Identical work to https://github.com/graphops/subgraph-radio/pull/18
=> chore: add labels workflow
